// Pure, dependency-free compounding interest calculator for the lending module.
// Kept as plain functions (no DB access) so the core money math is easy to
// unit test in isolation — this is the most safety-critical logic in the
// whole system, per the spec's "no black box" transparency requirement.
import Decimal from 'decimal.js';
import dayjs from 'dayjs';
import { money, ZERO } from '../common/money';

export interface RepaymentInput {
  date: Date;
  amount: Decimal;
}

export interface AccrualPeriod {
  periodStart: Date;
  periodEnd: Date;
  openingBalance: Decimal;
  interestRatePercentApplied: Decimal;
  interestCharged: Decimal;
  closingBalance: Decimal;
}

/**
 * Compounding rule (locked in by user decision): at each monthly anniversary
 * of the loan date, if the loan is still unpaid, interest = rate% of the
 * FULL outstanding balance at that moment (principal + all interest charged
 * so far, minus all repayments made so far) — not just the original principal.
 *
 * Example: $100 principal, 20%, unpaid 3 months straight:
 *   Month 1 close: $120.00 → Month 2 close: $144.00 → Month 3 close: $172.80
 *
 * `existingAccruals` are periods already recorded in the DB (immutable —
 * each keeps the rate that was in force when it was charged). `ratePercent`
 * is applied only to NEW periods generated by this call, so changing the
 * loan's rate takes effect going forward without rewriting history.
 */
export function computeNewAccruals(params: {
  principal: Decimal;
  dateGiven: Date;
  ratePercent: Decimal;
  existingAccruals: AccrualPeriod[]; // sorted by periodEnd ascending
  repayments: RepaymentInput[]; // sorted by date ascending
  asOf: Date;
}): AccrualPeriod[] {
  const { principal, dateGiven, ratePercent, existingAccruals, repayments, asOf } = params;
  const created: AccrualPeriod[] = [];
  let periodIndex = existingAccruals.length; // 0-based -> next period number is periodIndex+1

  // Running totals seeded from what's already recorded
  let interestChargedSoFar = existingAccruals.reduce(
    (s, a) => s.plus(a.interestCharged),
    ZERO,
  );

  // eslint-disable-next-line no-constant-condition
  while (true) {
    const periodEnd = dayjs(dateGiven).add(periodIndex + 1, 'month').toDate();
    if (periodEnd > asOf) break;

    const periodStart =
      periodIndex === 0
        ? dateGiven
        : dayjs(dateGiven).add(periodIndex, 'month').toDate();

    const repaymentsToDate = repayments
      .filter((r) => r.date <= periodEnd)
      .reduce((s, r) => s.plus(r.amount), ZERO);

    const openingBalance = principal.plus(interestChargedSoFar).minus(repaymentsToDate);

    if (openingBalance.lte(0)) {
      // Loan was fully settled before this period's anchor — nothing more to accrue.
      break;
    }

    const interestCharged = openingBalance.times(ratePercent).div(100);
    const closingBalance = openingBalance.plus(interestCharged);

    created.push({
      periodStart,
      periodEnd,
      openingBalance,
      interestRatePercentApplied: ratePercent,
      interestCharged,
      closingBalance,
    });

    interestChargedSoFar = interestChargedSoFar.plus(interestCharged);
    periodIndex += 1;
  }

  return created;
}

/** Outstanding balance at a point in time = principal + all interest charged
 *  up to that date − all repayments made up to that date. Never negative
 *  (a would-be-negative result means the loan is overpaid/settled → 0). */
export function computeOutstandingBalance(params: {
  principal: Decimal;
  accruals: { periodEnd: Date; interestCharged: Decimal }[];
  repayments: RepaymentInput[];
  asOf: Date;
}): Decimal {
  const { principal, accruals, repayments, asOf } = params;
  const interest = accruals
    .filter((a) => a.periodEnd <= asOf)
    .reduce((s, a) => s.plus(a.interestCharged), ZERO);
  const repaid = repayments
    .filter((r) => r.date <= asOf)
    .reduce((s, r) => s.plus(r.amount), ZERO);
  const balance = principal.plus(interest).minus(repaid);
  return balance.gt(0) ? balance : ZERO;
}

/** Interest-first repayment allocation (assumption stated in the architecture
 *  doc, section G — override here if you tell me you want principal-first). */
export function allocateRepayment(params: {
  amount: Decimal;
  totalInterestChargedToDate: Decimal;
  totalInterestAlreadyRepaid: Decimal;
}): { appliedToInterest: Decimal; appliedToPrincipal: Decimal } {
  const { amount, totalInterestChargedToDate, totalInterestAlreadyRepaid } = params;
  const outstandingInterest = totalInterestChargedToDate.minus(totalInterestAlreadyRepaid);
  const appliedToInterest = Decimal.min(amount, outstandingInterest.gt(0) ? outstandingInterest : ZERO);
  const appliedToPrincipal = amount.minus(appliedToInterest);
  return { appliedToInterest, appliedToPrincipal };
}
